export const searchDataColumns = [
  { field: "jigyosyoCode", headerName: "事業所コード", width: 110 },
  { field: "jigyosyoName", headerName: "事業所名", width: 220 },
  { field: "jigyosyoType", headerName: "事業所タイプ", width: 150 },
  { field: "jigyosyoPostalCode", headerName: "事業所〶", width: 90 },
  { field: "jigyosyoAddress", headerName: "事業所住所", width: 200 },
  { field: "jigyosyoTel", headerName: "事業所TEL", width: 110 },
  { field: "jigyosyoFax", headerName: "事業所FAX", width: 110 },
  { field: "jigyosyoReprName", headerName: "事業所代表者", width: 100 },
  {
    field: "jigyosyoReprPosition",
    headerName: "代表者役職",
    width: 120,
  },
  { field: "jigyosyoUrl", headerName: "事業所URL", width: 150 },
  {
    field: "jigyosyoReleaseDatetime",
    headerName: "厚労公開日時",
    width: 150,
  },
  { field: "companyCode", headerName: "法人コード", width: 130 },
  { field: "companyName", headerName: "法人名", width: 150 },
  { field: "companyKana", headerName: "法人名（かな）", width: 150 },
  { field: "companyPostalCode", headerName: "法人〶", width: 90 },
  { field: "companyAddress", headerName: "法人住所", width: 200 },
  { field: "companyTel", headerName: "法人電話番号", width: 110 },
  { field: "companyFax", headerName: "法人FAX番号", width: 110 },
  { field: "companyUrl", headerName: "法人URL", width: 150 },
  { field: "companyReprName", headerName: "法人代表者", width: 100 },
  { field: "companyReprPosition", headerName: "代表者役職", width: 120 },
  { field: "companyEstablishedDate", headerName: "設立日", width: 100 },
  { field: "companyReleaseDatetime", headerName: "厚労公開日時", width: 150 },
];
