# Generated by Django 4.2.5 on 2023-12-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0002_historicaljigyosyotransaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="company_code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalcompany",
            name="company_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaljigyosyo",
            name="jigyosyo_code",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="jigyosyo",
            name="jigyosyo_code",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="company",
            unique_together={("name", "address")},
        ),
    ]
