# Generated by Django 4.2.5 on 2023-12-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0003_alter_company_company_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljigyosyo",
            name="jigyosyo_code",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="jigyosyo",
            name="jigyosyo_code",
            field=models.CharField(max_length=255),
        ),
    ]
