# Generated by Django 4.2.5 on 2023-12-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0004_alter_historicaljigyosyo_jigyosyo_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljigyosyo",
            name="jigyosyo_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="jigyosyo",
            name="jigyosyo_code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
