# Generated by Django 4.2.5 on 2023-12-19 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0005_alter_historicaljigyosyo_jigyosyo_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="jigyosyo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="crm.jigyosyomanagement",
            ),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="jigyosyo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="crm.jigyosyomanagement",
            ),
        ),
    ]
