# Generated by Django 4.2.5 on 2023-12-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0006_alter_historicaljigyosyotransaction_jigyosyo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="visit_datetime",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="visit_datetime",
            field=models.DateField(),
        ),
    ]
