# Generated by Django 4.2.5 on 2024-01-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0007_alter_historicaljigyosyotransaction_visit_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="help_means",
            field=models.CharField(
                choices=[
                    ("houmon", "訪問"),
                    ("raihou_without_help", "来訪（支援なし）"),
                    ("raihou_with_help", "来訪（支援あり）"),
                    ("tel", "ＴＥＬ"),
                    ("online", "オンライン"),
                    ("fax", "ＦＡＸ"),
                    ("mail", "メール"),
                    ("koushu_sanka", "講習等参加"),
                    ("koushugo_shien", "講習後支援"),
                ],
                default="",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="help_status",
            field=models.CharField(
                choices=[
                    ("zero_help", "初めての支援"),
                    ("with_help", "支援歴有り"),
                    ("one_follow", "フォローアップ１回目"),
                    ("two_follow", "フォローアップ２回目"),
                ],
                default="",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="keikei_kubun",
            field=models.CharField(
                choices=[
                    ("shisetsu", "施設系"),
                    ("houmon", "訪問系"),
                    ("houmonshisetu", "施設訪問系"),
                ],
                default="hoge",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="help_means",
            field=models.CharField(
                choices=[
                    ("houmon", "訪問"),
                    ("raihou_without_help", "来訪（支援なし）"),
                    ("raihou_with_help", "来訪（支援あり）"),
                    ("tel", "ＴＥＬ"),
                    ("online", "オンライン"),
                    ("fax", "ＦＡＸ"),
                    ("mail", "メール"),
                    ("koushu_sanka", "講習等参加"),
                    ("koushugo_shien", "講習後支援"),
                ],
                default="hoge",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="help_status",
            field=models.CharField(
                choices=[
                    ("zero_help", "初めての支援"),
                    ("with_help", "支援歴有り"),
                    ("one_follow", "フォローアップ１回目"),
                    ("two_follow", "フォローアップ２回目"),
                ],
                default="hoge",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="keikei_kubun",
            field=models.CharField(
                choices=[
                    ("shisetsu", "施設系"),
                    ("houmon", "訪問系"),
                    ("houmonshisetu", "施設訪問系"),
                ],
                default="hoge",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
