# Generated by Django 4.2.5 on 2024-01-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0008_historicaljigyosyotransaction_help_means_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="jigyosyo",
            new_name="management",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="jigyosyo",
            new_name="management",
        ),
        migrations.AddField(
            model_name="historicaljigyosyo",
            name="exists_koyou_sekininsha",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyo",
            name="is_use_kaigo_machine_subsidy",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyo",
            name="is_use_other_subsidy",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyo",
            name="number_of_member",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="jigyosyo_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="jigyosyo_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="jigyosyo_exists_koyou_sekininsha",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="jigyosyo_fax_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="jigyosyo_is_use_kaigo_machine_subsidy",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="jigyosyo_is_use_other_subsidy",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="jigyosyo_kourou_release_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="jigyosyo_kourou_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="jigyosyo_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="jigyosyo_number_of_member",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="jigyosyo_postal_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="jigyosyo_repr_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="jigyosyo_repr_position",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="jigyosyo_tel_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="jigyosyo_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="management_description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="management_is_sanjo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jigyosyo",
            name="exists_koyou_sekininsha",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyo",
            name="is_use_kaigo_machine_subsidy",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyo",
            name="is_use_other_subsidy",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyo",
            name="number_of_member",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="jigyosyo_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="jigyosyo_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="jigyosyo_exists_koyou_sekininsha",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="jigyosyo_fax_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="jigyosyo_is_use_kaigo_machine_subsidy",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="jigyosyo_is_use_other_subsidy",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="jigyosyo_kourou_release_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="jigyosyo_kourou_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="jigyosyo_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="jigyosyo_number_of_member",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="jigyosyo_postal_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="jigyosyo_repr_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="jigyosyo_repr_position",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="jigyosyo_tel_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="jigyosyo_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="management_description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="management_is_sanjo",
            field=models.BooleanField(default=False),
        ),
    ]
