# Generated by Django 4.2.5 on 2024-01-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "crm",
            "0009_rename_jigyosyo_historicaljigyosyotransaction_management_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="jigyosyo_address",
            new_name="_jigyosyo_address",
        ),
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="jigyosyo_code",
            new_name="_jigyosyo_code",
        ),
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="jigyosyo_exists_koyou_sekininsha",
            new_name="_jigyosyo_exists_koyou_sekininsha",
        ),
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="jigyosyo_fax_number",
            new_name="_jigyosyo_fax_number",
        ),
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="jigyosyo_is_use_kaigo_machine_subsidy",
            new_name="_jigyosyo_is_use_kaigo_machine_subsidy",
        ),
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="jigyosyo_is_use_other_subsidy",
            new_name="_jigyosyo_is_use_other_subsidy",
        ),
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="jigyosyo_kourou_release_datetime",
            new_name="_jigyosyo_kourou_release_datetime",
        ),
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="jigyosyo_kourou_url",
            new_name="_jigyosyo_kourou_url",
        ),
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="jigyosyo_name",
            new_name="_jigyosyo_name",
        ),
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="jigyosyo_number_of_member",
            new_name="_jigyosyo_number_of_member",
        ),
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="jigyosyo_postal_code",
            new_name="_jigyosyo_postal_code",
        ),
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="jigyosyo_repr_name",
            new_name="_jigyosyo_repr_name",
        ),
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="jigyosyo_repr_position",
            new_name="_jigyosyo_repr_position",
        ),
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="jigyosyo_tel_number",
            new_name="_jigyosyo_tel_number",
        ),
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="jigyosyo_type",
            new_name="_jigyosyo_type",
        ),
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="management_description",
            new_name="_management_description",
        ),
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="management_is_sanjo",
            new_name="_management_is_sanjo",
        ),
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="visit_datetime",
            new_name="visit_date",
        ),
        migrations.RenameField(
            model_name="historicaljigyosyotransaction",
            old_name="content",
            new_name="visit_memo",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="jigyosyo_address",
            new_name="_jigyosyo_address",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="jigyosyo_code",
            new_name="_jigyosyo_code",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="jigyosyo_exists_koyou_sekininsha",
            new_name="_jigyosyo_exists_koyou_sekininsha",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="jigyosyo_fax_number",
            new_name="_jigyosyo_fax_number",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="jigyosyo_is_use_kaigo_machine_subsidy",
            new_name="_jigyosyo_is_use_kaigo_machine_subsidy",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="jigyosyo_is_use_other_subsidy",
            new_name="_jigyosyo_is_use_other_subsidy",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="jigyosyo_kourou_release_datetime",
            new_name="_jigyosyo_kourou_release_datetime",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="jigyosyo_kourou_url",
            new_name="_jigyosyo_kourou_url",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="jigyosyo_name",
            new_name="_jigyosyo_name",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="jigyosyo_number_of_member",
            new_name="_jigyosyo_number_of_member",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="jigyosyo_postal_code",
            new_name="_jigyosyo_postal_code",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="jigyosyo_repr_name",
            new_name="_jigyosyo_repr_name",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="jigyosyo_repr_position",
            new_name="_jigyosyo_repr_position",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="jigyosyo_tel_number",
            new_name="_jigyosyo_tel_number",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="jigyosyo_type",
            new_name="_jigyosyo_type",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="management_description",
            new_name="_management_description",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="management_is_sanjo",
            new_name="_management_is_sanjo",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="visit_datetime",
            new_name="visit_date",
        ),
        migrations.RenameField(
            model_name="jigyosyotransaction",
            old_name="content",
            new_name="visit_memo",
        ),
        migrations.RemoveField(
            model_name="historicaljigyosyotransaction",
            name="help_means",
        ),
        migrations.RemoveField(
            model_name="historicaljigyosyotransaction",
            name="help_status",
        ),
        migrations.RemoveField(
            model_name="jigyosyotransaction",
            name="help_means",
        ),
        migrations.RemoveField(
            model_name="jigyosyotransaction",
            name="help_status",
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="done_explain_support",
            field=models.BooleanField(blank=True, null=True, verbose_name="支援メニューの説明"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="done_knowing_problem",
            field=models.BooleanField(blank=True, null=True, verbose_name="課題の把握"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="is_accepting_intern",
            field=models.BooleanField(blank=True, null=True, verbose_name="介護実習の受入"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="is_going_to_recruit",
            field=models.BooleanField(blank=True, null=True, verbose_name="募集予定"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="is_recruiting_on_expect_hw",
            field=models.BooleanField(blank=True, null=True, verbose_name="ＨＷ以外に募集予定"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="is_recruiting_on_hw",
            field=models.BooleanField(blank=True, null=True, verbose_name="ＨＷに募集中"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_care_services_consult",
            field=models.BooleanField(blank=True, null=True, verbose_name="介護サービスの相談"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_care_services_inform",
            field=models.BooleanField(blank=True, null=True, verbose_name="介護サービスの情報"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_employment_management_responsibility_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="雇用管理責任者関係の相談"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_employment_management_responsibility_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="雇用管理責任者関係の情報"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_job_posting_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="雇用管理にかかる求人求職の相談"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_job_posting_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="雇用管理にかかる求人求職の情報"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_other_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="雇用管理に係るその他の相談"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_other_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="雇用管理に係るその他の情報"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_skill_development_consult",
            field=models.BooleanField(blank=True, null=True, verbose_name="能力開発の相談"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_skill_development_inform",
            field=models.BooleanField(blank=True, null=True, verbose_name="能力開発の情報"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_subsidies_consult",
            field=models.BooleanField(blank=True, null=True, verbose_name="助成金の相談"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_subsidies_inform",
            field=models.BooleanField(blank=True, null=True, verbose_name="助成金の情報"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_welfare_benefits_consult",
            field=models.BooleanField(blank=True, null=True, verbose_name="福利厚生の相談"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_welfare_benefits_inform",
            field=models.BooleanField(blank=True, null=True, verbose_name="福利厚生の情報"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_working_conditions_consult",
            field=models.BooleanField(blank=True, null=True, verbose_name="労働条件の相談"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_working_conditions_inform",
            field=models.BooleanField(blank=True, null=True, verbose_name="労働条件の情報"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_workplace_communication_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="職場のコミュニケーションの相談"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_workplace_communication_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="職場のコミュニケーションの情報"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_workplace_environment_consult",
            field=models.BooleanField(blank=True, null=True, verbose_name="職場環境の相談"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_workplace_environment_inform",
            field=models.BooleanField(blank=True, null=True, verbose_name="職場環境の情報"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="noukai_job_posting_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="能力開発にかかる求人求職の相談"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="noukai_job_posting_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="能力開発にかかる求人求職の情報"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="noukai_other_skill_development_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="能力開発に係るその他の相談"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="noukai_other_skill_development_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="能力開発に係るその他の情報"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="noukai_qualification_system_training_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="資格制度研修情報の相談"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="noukai_qualification_system_training_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="資格制度研修情報の情報"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="noukai_subsidy_system_for_skill_development_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="能力開発にかかる助成制度関係の相談"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="noukai_subsidy_system_for_skill_development_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="能力開発にかかる助成制度関係の情報"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="noukai_training_plan_curriculum_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="研修計画カリキュラム策定の相談"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="noukai_training_plan_curriculum_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="研修計画カリキュラム策定の情報"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="noukai_vocational_skill_development_promoter_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="職業能力開発推進者関係の相談"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="noukai_vocational_skill_development_promoter_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="職業能力開発推進者関係の情報"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="support_means",
            field=models.CharField(
                choices=[
                    ("houmon", "訪問"),
                    ("raihou_without_support", "来訪（支援なし）"),
                    ("raihou_with_support", "来訪（支援あり）"),
                    ("tel", "ＴＥＬ"),
                    ("online", "オンライン"),
                    ("fax", "ＦＡＸ"),
                    ("mail", "メール"),
                    ("koushu_sanka", "講習等参加"),
                    ("koushugo_shien", "講習後支援"),
                ],
                default="",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="support_status",
            field=models.CharField(
                choices=[
                    ("zero_support", "初めての支援"),
                    ("with_support", "支援歴有り"),
                    ("one_follow", "フォローアップ１回目"),
                    ("two_follow", "フォローアップ２回目"),
                ],
                default="",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="will_inform_hw",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="労働局（ＨＷ）への伝達"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="will_inform_others",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="その他の関係機関への伝達"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="will_inform_prefecture",
            field=models.BooleanField(blank=True, null=True, verbose_name="都道府県への伝達"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="with_alone_on_hw",
            field=models.BooleanField(blank=True, null=True, verbose_name="労働局委託で単独"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="with_employment_consultant",
            field=models.BooleanField(blank=True, null=True, verbose_name="雇用コンサルと同行"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="with_health_counselor",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="ヘルスカウンセラーと同行"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="with_staff_on_hw",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="労働局委託で職員と同行"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="with_tool_utilization",
            field=models.BooleanField(blank=True, null=True, verbose_name="ツールの活用"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="with_training_coordinator",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="研修コーディネーターと同行"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="done_explain_support",
            field=models.BooleanField(blank=True, null=True, verbose_name="支援メニューの説明"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="done_knowing_problem",
            field=models.BooleanField(blank=True, null=True, verbose_name="課題の把握"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="is_accepting_intern",
            field=models.BooleanField(blank=True, null=True, verbose_name="介護実習の受入"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="is_going_to_recruit",
            field=models.BooleanField(blank=True, null=True, verbose_name="募集予定"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="is_recruiting_on_expect_hw",
            field=models.BooleanField(blank=True, null=True, verbose_name="ＨＷ以外に募集予定"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="is_recruiting_on_hw",
            field=models.BooleanField(blank=True, null=True, verbose_name="ＨＷに募集中"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_care_services_consult",
            field=models.BooleanField(blank=True, null=True, verbose_name="介護サービスの相談"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_care_services_inform",
            field=models.BooleanField(blank=True, null=True, verbose_name="介護サービスの情報"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_employment_management_responsibility_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="雇用管理責任者関係の相談"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_employment_management_responsibility_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="雇用管理責任者関係の情報"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_job_posting_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="雇用管理にかかる求人求職の相談"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_job_posting_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="雇用管理にかかる求人求職の情報"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_other_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="雇用管理に係るその他の相談"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_other_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="雇用管理に係るその他の情報"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_skill_development_consult",
            field=models.BooleanField(blank=True, null=True, verbose_name="能力開発の相談"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_skill_development_inform",
            field=models.BooleanField(blank=True, null=True, verbose_name="能力開発の情報"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_subsidies_consult",
            field=models.BooleanField(blank=True, null=True, verbose_name="助成金の相談"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_subsidies_inform",
            field=models.BooleanField(blank=True, null=True, verbose_name="助成金の情報"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_welfare_benefits_consult",
            field=models.BooleanField(blank=True, null=True, verbose_name="福利厚生の相談"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_welfare_benefits_inform",
            field=models.BooleanField(blank=True, null=True, verbose_name="福利厚生の情報"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_working_conditions_consult",
            field=models.BooleanField(blank=True, null=True, verbose_name="労働条件の相談"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_working_conditions_inform",
            field=models.BooleanField(blank=True, null=True, verbose_name="労働条件の情報"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_workplace_communication_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="職場のコミュニケーションの相談"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_workplace_communication_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="職場のコミュニケーションの情報"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_workplace_environment_consult",
            field=models.BooleanField(blank=True, null=True, verbose_name="職場環境の相談"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_workplace_environment_inform",
            field=models.BooleanField(blank=True, null=True, verbose_name="職場環境の情報"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="noukai_job_posting_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="能力開発にかかる求人求職の相談"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="noukai_job_posting_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="能力開発にかかる求人求職の情報"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="noukai_other_skill_development_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="能力開発に係るその他の相談"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="noukai_other_skill_development_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="能力開発に係るその他の情報"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="noukai_qualification_system_training_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="資格制度研修情報の相談"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="noukai_qualification_system_training_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="資格制度研修情報の情報"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="noukai_subsidy_system_for_skill_development_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="能力開発にかかる助成制度関係の相談"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="noukai_subsidy_system_for_skill_development_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="能力開発にかかる助成制度関係の情報"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="noukai_training_plan_curriculum_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="研修計画カリキュラム策定の相談"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="noukai_training_plan_curriculum_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="研修計画カリキュラム策定の情報"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="noukai_vocational_skill_development_promoter_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="職業能力開発推進者関係の相談"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="noukai_vocational_skill_development_promoter_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="職業能力開発推進者関係の情報"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="support_means",
            field=models.CharField(
                choices=[
                    ("houmon", "訪問"),
                    ("raihou_without_support", "来訪（支援なし）"),
                    ("raihou_with_support", "来訪（支援あり）"),
                    ("tel", "ＴＥＬ"),
                    ("online", "オンライン"),
                    ("fax", "ＦＡＸ"),
                    ("mail", "メール"),
                    ("koushu_sanka", "講習等参加"),
                    ("koushugo_shien", "講習後支援"),
                ],
                default="",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="support_status",
            field=models.CharField(
                choices=[
                    ("zero_support", "初めての支援"),
                    ("with_support", "支援歴有り"),
                    ("one_follow", "フォローアップ１回目"),
                    ("two_follow", "フォローアップ２回目"),
                ],
                default="",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="will_inform_hw",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="労働局（ＨＷ）への伝達"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="will_inform_others",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="その他の関係機関への伝達"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="will_inform_prefecture",
            field=models.BooleanField(blank=True, null=True, verbose_name="都道府県への伝達"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="with_alone_on_hw",
            field=models.BooleanField(blank=True, null=True, verbose_name="労働局委託で単独"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="with_employment_consultant",
            field=models.BooleanField(blank=True, null=True, verbose_name="雇用コンサルと同行"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="with_health_counselor",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="ヘルスカウンセラーと同行"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="with_staff_on_hw",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="労働局委託で職員と同行"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="with_tool_utilization",
            field=models.BooleanField(blank=True, null=True, verbose_name="ツールの活用"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="with_training_coordinator",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="研修コーディネーターと同行"
            ),
        ),
    ]
