# Generated by Django 4.2.5 on 2024-01-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "crm",
            "0010_rename_jigyosyo_address_historicaljigyosyotransaction__jigyosyo_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="keikei_kubun",
            field=models.CharField(
                blank=True,
                choices=[
                    ("shisetsu", "施設系"),
                    ("houmon", "訪問系"),
                    ("houmonshisetu", "施設訪問系"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="support_means",
            field=models.CharField(
                blank=True,
                choices=[
                    ("houmon", "訪問"),
                    ("raihou_without_support", "来訪（支援なし）"),
                    ("raihou_with_support", "来訪（支援あり）"),
                    ("tel", "ＴＥＬ"),
                    ("online", "オンライン"),
                    ("fax", "ＦＡＸ"),
                    ("mail", "メール"),
                    ("koushu_sanka", "講習等参加"),
                    ("koushugo_shien", "講習後支援"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="support_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zero_support", "初めての支援"),
                    ("with_support", "支援歴有り"),
                    ("one_follow", "フォローアップ１回目"),
                    ("two_follow", "フォローアップ２回目"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="visit_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="visit_memo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="keikei_kubun",
            field=models.CharField(
                blank=True,
                choices=[
                    ("shisetsu", "施設系"),
                    ("houmon", "訪問系"),
                    ("houmonshisetu", "施設訪問系"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="support_means",
            field=models.CharField(
                blank=True,
                choices=[
                    ("houmon", "訪問"),
                    ("raihou_without_support", "来訪（支援なし）"),
                    ("raihou_with_support", "来訪（支援あり）"),
                    ("tel", "ＴＥＬ"),
                    ("online", "オンライン"),
                    ("fax", "ＦＡＸ"),
                    ("mail", "メール"),
                    ("koushu_sanka", "講習等参加"),
                    ("koushugo_shien", "講習後支援"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="support_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zero_support", "初めての支援"),
                    ("with_support", "支援歴有り"),
                    ("one_follow", "フォローアップ１回目"),
                    ("two_follow", "フォローアップ２回目"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="visit_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="visit_memo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
