# Generated by Django 4.2.5 on 2024-01-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0013_historicaljigyosyo_custom_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="jigyosyo_info",
            field=models.CharField(
                blank=True,
                choices=[
                    ("under_fifty", "５０人以下"),
                    ("before_establishment", "開業前"),
                    ("within_three_establishment", "開業３年未満"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="jigyosyo_info",
            field=models.CharField(
                blank=True,
                choices=[
                    ("under_fifty", "５０人以下"),
                    ("before_establishment", "開業前"),
                    ("within_three_establishment", "開業３年未満"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
