# Generated by Django 4.2.5 on 2024-01-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0014_historicaljigyosyotransaction_jigyosyo_info_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaljigyosyo",
            name="exists_koyou_sekininsha",
        ),
        migrations.RemoveField(
            model_name="historicaljigyosyo",
            name="is_use_kaigo_machine_subsidy",
        ),
        migrations.RemoveField(
            model_name="historicaljigyosyo",
            name="is_use_other_subsidy",
        ),
        migrations.RemoveField(
            model_name="historicaljigyosyotransaction",
            name="_jigyosyo_exists_koyou_sekininsha",
        ),
        migrations.RemoveField(
            model_name="historicaljigyosyotransaction",
            name="_jigyosyo_is_use_kaigo_machine_subsidy",
        ),
        migrations.RemoveField(
            model_name="historicaljigyosyotransaction",
            name="_jigyosyo_is_use_other_subsidy",
        ),
        migrations.RemoveField(
            model_name="historicaljigyosyotransaction",
            name="jigyosyo_info",
        ),
        migrations.RemoveField(
            model_name="jigyosyo",
            name="exists_koyou_sekininsha",
        ),
        migrations.RemoveField(
            model_name="jigyosyo",
            name="is_use_kaigo_machine_subsidy",
        ),
        migrations.RemoveField(
            model_name="jigyosyo",
            name="is_use_other_subsidy",
        ),
        migrations.RemoveField(
            model_name="jigyosyotransaction",
            name="_jigyosyo_exists_koyou_sekininsha",
        ),
        migrations.RemoveField(
            model_name="jigyosyotransaction",
            name="_jigyosyo_is_use_kaigo_machine_subsidy",
        ),
        migrations.RemoveField(
            model_name="jigyosyotransaction",
            name="_jigyosyo_is_use_other_subsidy",
        ),
        migrations.RemoveField(
            model_name="jigyosyotransaction",
            name="jigyosyo_info",
        ),
        migrations.AddField(
            model_name="historicaljigyosyo",
            name="koyoukanri_sekinin_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="_jigyosyo_koyoukanri_sekinin_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="exists_koyoukanri",
            field=models.BooleanField(blank=True, null=True, verbose_name="雇用管理責任者の有無"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="exists_sekininkousyu",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="責任者講習経験者の有無"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="is_before_establishment",
            field=models.BooleanField(blank=True, null=True, verbose_name="開業前"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="is_under_fifty",
            field=models.BooleanField(blank=True, null=True, verbose_name="５０人以下"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="is_within_three_years_since_estabrishment",
            field=models.BooleanField(blank=True, null=True, verbose_name="開業３年未満"),
        ),
        migrations.AddField(
            model_name="jigyosyo",
            name="koyoukanri_sekinin_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="_jigyosyo_koyoukanri_sekinin_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="exists_koyoukanri",
            field=models.BooleanField(blank=True, null=True, verbose_name="雇用管理責任者の有無"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="exists_sekininkousyu",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="責任者講習経験者の有無"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="is_before_establishment",
            field=models.BooleanField(blank=True, null=True, verbose_name="開業前"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="is_under_fifty",
            field=models.BooleanField(blank=True, null=True, verbose_name="５０人以下"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="is_within_three_years_since_estabrishment",
            field=models.BooleanField(blank=True, null=True, verbose_name="開業３年未満"),
        ),
    ]
