# Generated by Django 4.2.5 on 2024-01-30 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0015_remove_historicaljigyosyo_exists_koyou_sekininsha_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionStaffDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_name", models.CharField(max_length=255, verbose_name="スタッフ名")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("branch_manager", "支部長"),
                            ("instructor", "インストラクター"),
                            ("advisor", "アドバイザー"),
                            ("other", "その他"),
                        ],
                        max_length=50,
                        verbose_name="役職",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_details",
                        to="crm.jigyosyotransaction",
                    ),
                ),
            ],
        ),
    ]
