# Generated by Django 4.2.5 on 2024-01-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0016_transactionstaffdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="is_dedicated",
            field=models.BooleanField(blank=True, null=True, verbose_name="専任済み"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="is_participated",
            field=models.BooleanField(blank=True, null=True, verbose_name="過去に受講者あり"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="is_dedicated",
            field=models.BooleanField(blank=True, null=True, verbose_name="専任済み"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="is_participated",
            field=models.BooleanField(blank=True, null=True, verbose_name="過去に受講者あり"),
        ),
    ]
