# Generated by Django 4.2.5 on 2024-01-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0017_historicaljigyosyotransaction_is_dedicated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaljigyosyotransaction",
            name="koyou_workplace_environment_consult",
        ),
        migrations.RemoveField(
            model_name="historicaljigyosyotransaction",
            name="koyou_workplace_environment_inform",
        ),
        migrations.RemoveField(
            model_name="jigyosyotransaction",
            name="koyou_workplace_environment_consult",
        ),
        migrations.RemoveField(
            model_name="jigyosyotransaction",
            name="koyou_workplace_environment_inform",
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_workplace_environment_ict_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="職場環境（ICT）の相談"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_workplace_environment_ict_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="職場環境（ICT）の情報"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_workplace_environment_philosophy_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="職場環境（理念）の相談"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="koyou_workplace_environment_philosophy_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="職場環境（理念）の情報"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_workplace_environment_ict_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="職場環境（ICT）の相談"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_workplace_environment_ict_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="職場環境（ICT）の情報"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_workplace_environment_philosophy_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="職場環境（理念）の相談"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="koyou_workplace_environment_philosophy_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="職場環境（理念）の情報"
            ),
        ),
    ]
