# Generated by Django 4.2.5 on 2024-01-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "crm",
            "0018_remove_historicaljigyosyotransaction_koyou_workplace_environment_consult_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="is_use_kaigo_machine_subsidy",
            field=models.BooleanField(blank=True, null=True, verbose_name="介護機器助成金の使用"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="is_use_other_subsidy",
            field=models.BooleanField(blank=True, null=True, verbose_name="その他の助成金の使用"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="is_use_kaigo_machine_subsidy",
            field=models.BooleanField(blank=True, null=True, verbose_name="介護機器助成金の使用"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="is_use_other_subsidy",
            field=models.BooleanField(blank=True, null=True, verbose_name="その他の助成金の使用"),
        ),
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="is_dedicated",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="雇用管理責任者選任の有無"
            ),
        ),
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="is_participated",
            field=models.BooleanField(blank=True, null=True, verbose_name="責任者講習受講の有無"),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="is_dedicated",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="雇用管理責任者選任の有無"
            ),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="is_participated",
            field=models.BooleanField(blank=True, null=True, verbose_name="責任者講習受講の有無"),
        ),
    ]
