# Generated by Django 4.2.5 on 2024-01-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "crm",
            "0019_historicaljigyosyotransaction_is_use_kaigo_machine_subsidy_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="shubetsu",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="historicalcompany",
            old_name="shubetsu",
            new_name="type",
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="_company_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="法人種別"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="_company_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="法人種別"
            ),
        ),
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="_jigyosyo_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="事業所種別"
            ),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="_jigyosyo_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="事業所種別"
            ),
        ),
    ]
