# Generated by Django 4.2.5 on 2024-01-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0020_rename_shubetsu_company_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="_company_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="法人名"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="_management_koyoukanri_memo",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="雇用管理者専任状況"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="_company_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="法人名"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="_management_koyoukanri_memo",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="雇用管理者専任状況"
            ),
        ),
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="_jigyosyo_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="事業所住所"
            ),
        ),
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="_jigyosyo_number_of_member",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="職員数"
            ),
        ),
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="_jigyosyo_repr_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="事業所代表者名"
            ),
        ),
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="_jigyosyo_tel_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="事業所電話番号"
            ),
        ),
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="_jigyosyo_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="サービス種別"
            ),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="_jigyosyo_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="事業所住所"
            ),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="_jigyosyo_number_of_member",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="職員数"
            ),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="_jigyosyo_repr_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="事業所代表者名"
            ),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="_jigyosyo_tel_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="事業所電話番号"
            ),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="_jigyosyo_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="サービス種別"
            ),
        ),
    ]
