# Generated by Django 4.2.5 on 2024-02-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "crm",
            "0022_historicaljigyosyotransaction__jigyosyo_established_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="_management_is_sanjo",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="_management_is_sanjo",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
