# Generated by Django 4.2.5 on 2024-02-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "crm",
            "0023_alter_historicaljigyosyotransaction__management_is_sanjo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="koyou_workplace_environment_ict_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="生産性向上（ICT）の相談"
            ),
        ),
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="koyou_workplace_environment_ict_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="生産性向上（ICT）の情報"
            ),
        ),
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="koyou_workplace_environment_philosophy_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="理念・教育・環境の相談"
            ),
        ),
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="koyou_workplace_environment_philosophy_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="理念・教育・環境の情報"
            ),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="koyou_workplace_environment_ict_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="生産性向上（ICT）の相談"
            ),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="koyou_workplace_environment_ict_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="生産性向上（ICT）の情報"
            ),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="koyou_workplace_environment_philosophy_consult",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="理念・教育・環境の相談"
            ),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="koyou_workplace_environment_philosophy_inform",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="理念・教育・環境の情報"
            ),
        ),
    ]
