# Generated by Django 4.2.5 on 2024-02-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "crm",
            "0024_alter_historicaljigyosyotransaction_koyou_workplace_environment_ict_consult_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaljigyosyotransaction",
            name="is_use_kaigo_machine_subsidy",
        ),
        migrations.RemoveField(
            model_name="historicaljigyosyotransaction",
            name="is_use_other_subsidy",
        ),
        migrations.RemoveField(
            model_name="jigyosyotransaction",
            name="is_use_kaigo_machine_subsidy",
        ),
        migrations.RemoveField(
            model_name="jigyosyotransaction",
            name="is_use_other_subsidy",
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="is_use_subsidy",
            field=models.BooleanField(blank=True, null=True, verbose_name="助成金の活用状況"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="is_use_subsidy",
            field=models.BooleanField(blank=True, null=True, verbose_name="助成金の活用状況"),
        ),
    ]
