# Generated by Django 4.2.5 on 2024-02-07 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "crm",
            "0025_remove_historicaljigyosyotransaction_is_use_kaigo_machine_subsidy_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaljigyosyotransaction",
            name="with_tool_utilization",
        ),
        migrations.RemoveField(
            model_name="jigyosyotransaction",
            name="with_tool_utilization",
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="tool_utilization_business_manual",
            field=models.BooleanField(blank=True, null=True, verbose_name="業務推進マニュアル"),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="tool_utilization_check_action",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="CHECK&ACTION"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="tool_utilization_others",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="その他（ツール内容は「支援内容・把握した課題等」に記載）"
            ),
        ),
        migrations.AddField(
            model_name="historicaljigyosyotransaction",
            name="tool_utilization_shibu_document",
            field=models.BooleanField(blank=True, null=True, verbose_name="支部作成の資料"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="tool_utilization_business_manual",
            field=models.BooleanField(blank=True, null=True, verbose_name="業務推進マニュアル"),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="tool_utilization_check_action",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="CHECK&ACTION"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="tool_utilization_others",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="その他（ツール内容は「支援内容・把握した課題等」に記載）"
            ),
        ),
        migrations.AddField(
            model_name="jigyosyotransaction",
            name="tool_utilization_shibu_document",
            field=models.BooleanField(blank=True, null=True, verbose_name="支部作成の資料"),
        ),
        migrations.AlterField(
            model_name="historicaljigyosyotransaction",
            name="_company_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("public", "会社（民間事業者）"),
                    ("welfare", "社会福祉法人"),
                    ("medical", "医療法人"),
                    ("shouhi", "消費生活共同組合等"),
                    ("koueki", "公益法人等"),
                    ("nonprofit", "特定非営利活動法人"),
                    ("job_center", "職業紹介事業所"),
                    ("home_helper", "ホームヘルパー等個人"),
                    ("publicity", "公営施設等"),
                    ("municipality", "市町村等公共機関"),
                    ("koushu_member", "講習等参加者"),
                ],
                max_length=255,
                null=True,
                verbose_name="法人種別",
            ),
        ),
        migrations.AlterField(
            model_name="jigyosyotransaction",
            name="_company_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("public", "会社（民間事業者）"),
                    ("welfare", "社会福祉法人"),
                    ("medical", "医療法人"),
                    ("shouhi", "消費生活共同組合等"),
                    ("koueki", "公益法人等"),
                    ("nonprofit", "特定非営利活動法人"),
                    ("job_center", "職業紹介事業所"),
                    ("home_helper", "ホームヘルパー等個人"),
                    ("publicity", "公営施設等"),
                    ("municipality", "市町村等公共機関"),
                    ("koushu_member", "講習等参加者"),
                ],
                max_length=255,
                null=True,
                verbose_name="法人種別",
            ),
        ),
        migrations.AlterField(
            model_name="transactionstaffdetail",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("branch_manager", "支部長"),
                    ("instructor", "インストラクター"),
                    ("advisor", "アドバイザー"),
                    ("other", "その他"),
                ],
                max_length=50,
                null=True,
                verbose_name="役職",
            ),
        ),
        migrations.AlterField(
            model_name="transactionstaffdetail",
            name="staff_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="スタッフ名"
            ),
        ),
        migrations.AlterField(
            model_name="transactionstaffdetail",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_details",
                to="crm.jigyosyotransaction",
            ),
        ),
    ]
