# Generated by Django 4.2.5 on 2024-02-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0031_rename_type_historicaljigyosyo_service_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljigyosyo",
            name="established_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyo",
            name="established_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
