# Generated by Django 4.2.5 on 2024-02-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0032_historicaljigyosyo_established_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljigyosyo",
            name="turnover_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaljigyosyo",
            name="url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyo",
            name="turnover_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyo",
            name="url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
