# Generated by Django 4.2.5 on 2024-02-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0033_historicaljigyosyo_turnover_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljigyosyo",
            name="sanjo_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jigyosyo",
            name="sanjo_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
